library(Rcpp)
library(RcppArmadillo)
library(pdist)
source('get_inner.R')
source('W.gen.R')
source('getInner.R')
source('getInner.itrfit.dif.R')
source('pred.R')
source('itrFit.R')
source('predict.itrfit.R')
sourceCpp('diffit_C.cpp')

train=read.csv('train.csv')
x=train[, 2:201];y=train$y_train
res=itrFit(x, y, 1, 1, 1, method='logistic', kernel='gaussian', lambda=10^(-10:2))
fity=predict(res, option='normal')
plot(x[,1:2], col=fity)
fity=predict(res, newdata = x_tune,option='normal', index=9)
plot(x[,1:2], col=fity)
